USE AstronomicalEvents2
GO

-- a doua
-- Problema:
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
	BEGIN TRAN
	SELECT * FROM observatory
	WAITFOR DELAY '00:00:13'
	SELECT * FROM observatory
COMMIT TRAN
-- Problema: UNCOMMITTED