USE AstronomicalEvents2
GO

-- a doua
-- PROBLEM : 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	print 'SELECT 1'
	SELECT * FROM observatory
	WAITFOR DELAY '00:00:15'
	print 'SELECT 2'
	SELECT * FROM observatory
COMMIT TRAN;


DELETE FROM observatory WHERE NAME LIKE 'Planetarium Brasov';