-- User table
CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   	first_name CHARACTER VARYING(50) NOT NULL,
   	last_name CHARACTER VARYING(50) NOT NULL,
	email CHARACTER VARYING(50) NOT NULL
);

-- Friendship table
CREATE TABLE friendships (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user1Id BIGINT,
    user2Id BIGINT,
	friendsFrom TIMESTAMP,
    FOREIGN KEY (user1Id) REFERENCES users(id),
    FOREIGN KEY (user2Id) REFERENCES users(id)
);
